name: 'terragrunt-atlantis-config'
description: 'Checks if the atlantis.yaml file is up to date'
branding:
  icon: file-text
  color: blue
inputs:
  version:
    description: 'Revision of terragrunt-atlantis-config to use'
    required: true
    default: 'v0.4.3'
  extra_args:
    description: 'Extra args to pass to `terragrunt-atlantis-config generate`. The `output` flag should not be specified.'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.extra_args }}